dubbo:
  application:
    name: item-web
  registry:
    protocol: zookeeper
    address: 192.168.216.129:2181
server:
  port: 9093
spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.216.129
    virtual-host: /java1902
    port: 5672
    username: admin
    password: admin