spring:
  mail:
    host: smtp.163.com
    username: maizifeng@163.com
    password: asd369874125000
    default-encoding: utf-8
    port: 465
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          port: 465
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
mail:
  fromAdd: maizifeng@163.com
  toAdd: maizifeng@163.com